apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    name: dbpvc1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-db
  resources:
    requests:
      storage: 1Gi
