kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-db
  hostPath:
    path: "/mnt/db"
